const API = window.HMO_API_URL || "https://hmo-doctor-finder-api.onrender.com";
let currentDoctors = [];
let selectedDoctor = null;
const $ = id => document.getElementById(id);
function initials(name){return name.replace("Dr. ","").split(" ").map(x=>x[0]).slice(0,2).join("")}
function addOptions(id, values){const el=$(id);values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)})}
async function loadMeta(){try{const r=await fetch(`${API}/meta`);if(!r.ok)throw new Error();const data=await r.json();addOptions("hmo",data.hmos);addOptions("specialty",data.specialties);addOptions("location",data.locations);$("apiStatus").textContent="API connected";$("apiStatus").style.color="#0b806c"}catch(e){$("apiStatus").textContent="API unavailable";$("apiStatus").style.color="#b04a3f"}}
function params(){const p=new URLSearchParams();if($("hmo").value)p.set("hmo",$("hmo").value);if($("specialty").value)p.set("specialty",$("specialty").value);if($("location").value)p.set("location",$("location").value);if($("patientType").value)p.set("patient_type",$("patientType").value);if($("teleconsult").checked)p.set("teleconsult","true");if($("verified").checked)p.set("verified_only","true");p.set("min_rating",$("rating").value);p.set("min_experience",$("experience").value);return p.toString()}
async function search(){try{const r=await fetch(`${API}/doctors?${params()}`);if(!r.ok)throw new Error();const data=await r.json();currentDoctors=data.items;render()}catch(e){$("count").textContent="API unavailable";$("list").innerHTML=`<div class="doctor-card"><div>The backend API is currently unavailable.</div></div>`}}
function render(){$("count").textContent=`${currentDoctors.length} doctor${currentDoctors.length===1?"":"s"} found`;$("list").innerHTML=currentDoctors.map(d=>`<article class="doctor-card"><div class="doctor-main"><div class="avatar">${initials(d.name)}</div><div><div class="name">${d.name}</div><div class="spec">${d.specialty}</div><div class="meta">${d.clinic} • ${d.location}<br>${d.experience_years} years experience</div><div class="badges">${d.hmos.map(h=>`<span class="badge">${h}</span>`).join("")}${d.teleconsult?`<span class="badge green">Teleconsult</span>`:""}${d.verified?`<span class="badge green">HMO verified</span>`:`<span class="badge">Needs verification</span>`}</div></div></div><div class="side"><div class="rating">★ ${d.rating}</div><div class="avail">${d.next_available}</div><button onclick="openBooking(${d.id})">Request Appointment</button></div></article>`).join("")}
window.openBooking=id=>{selectedDoctor=currentDoctors.find(d=>d.id===id);$("doctorName").textContent=selectedDoctor.name;$("doctorMeta").textContent=`${selectedDoctor.specialty} • ${selectedDoctor.clinic}`;$("apptHmo").innerHTML=selectedDoctor.hmos.map(h=>`<option>${h}</option>`).join("");$("success").classList.add("hidden");$("modal").classList.remove("hidden")}
$("closeModal").onclick=()=>$("modal").classList.add("hidden");$("modal").onclick=e=>{if(e.target.id==="modal")$("modal").classList.add("hidden")}
$("submitAppt").onclick=async()=>{const payload={doctor_id:selectedDoctor.id,patient_name:$("patientName").value.trim(),hmo_provider:$("apptHmo").value,membership_no:$("memberNo").value.trim()||null,preferred_date:$("date").value,consultation_type:$("consultType").value};if(!payload.patient_name||!payload.preferred_date){$("success").textContent="Enter the patient name and preferred date.";$("success").classList.remove("hidden");return}const r=await fetch(`${API}/appointments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();$("success").textContent=r.ok?`Request created. Status: ${data.status}. Reference: ${data.id.slice(0,8)}`:(data.detail||"Unable to create request.");$("success").classList.remove("hidden")}
$("searchBtn").onclick=search;loadMeta().then(search);